---
    - debug: msg="Play_hosts={{play_hosts}}"
      run_once: true
      tags: always

    - set_fact:
         scripttype: "{{ scripttorun.split('.')[1] }}"
         script: "{{ scripttorun | basename }}"
         db2ilist: "{{ db2inst | default('') }}"
      tags: always

    - name: Copy - Script to target node
      copy: src="{{ scripttorun }}" dest="/tmp/{{ script }}" mode=0755
      ignore_errors: true
      tags: copy

    - import_tasks: run_as_all_incs.yml
      when: db2ilist == "all"

    - import_tasks: run_as_one_inc.yml
      when: db2ilist != "all"

    - name: "Fetch - Out file from target node to controller - {{ fetchdir }} dir"
      fetch: src="/tmp/{{ script }}_out.txt" dest="{{ fetchdir }}/{{ script }}_out_{{ inventory_hostname }}.txt" flat=yes
      ignore_errors: true
      tags: fetch

    - name: Remove - Files from target nodes.
      file: path="{{ item }}" state=absent
      loop:
        - "/tmp/{{ script }}"
        - "/tmp/{{ script }}_out.txt"
      tags: remove