---

    - debug: msg="Play_hosts={{play_hosts}}"
      run_once: true

    - stat: path="{{ pvtgtdir }}/db2patch.running"
      register: runfile
      tags: always

    - stat: path="{{ pvtgtdir }}/db2patch.complete"
      register: complete
      tags: always

    - name: Run - prereq steps
      import_tasks: "pre_reqs.yaml"
      when: not runfile.stat.exists and
            not complete.stat.exists
      tags: prereq

    - name: Run - hadr_roles and todolist scripts
      shell: "sh {{ scriptsdir }}/{{ item }}"
      loop:
        - hadr_roles.sh
        - todolist.sh
      when: not runfile.stat.exists and
            not complete.stat.exists
      tags: hadr_roles,runtodo

    - name: Create - Steps to run on Standbys or Stand-Alone or client db2 servers
      shell:
        cmd: ls STAGE01.DB2STEP*.*.TODO | sed -e "s/\.TODO//g"
        chdir: "{{ stepsdir }}"
      register: todos1
      failed_when: todos1.rc > 1
      when: not complete.stat.exists
      tags: todos,main

    - name: Create - Steps to run on Primary db2 server
      shell:
        cmd: ls STAGE02.DB2STEP*.*.TODO | sed -e "s/\.TODO//g"
        chdir: "{{ stepsdir }}"
      register: todos2
      failed_when: todos1.rc > 1
      when: not complete.stat.exists
      tags: todos,main

    - name: Info - Steps to run on Standbys or Stand-alone or client db2 Server
      debug:
        msg: "{{ todos1.stdout }}"
      when: not complete.stat.exists
      ignore_errors: true
      tags: todos,main

    - name: Info - Steps to run on Primary Server
      debug:
        msg: "{{ todos2.stdout }}"
      when: not complete.stat.exists
      ignore_errors: true
      tags: todos,main

    - name: Run - Steps on Standbys or client or Stand-Alone
      shell:
        cmd: "if ( sh {{ item }}.TODO ); then mv {{ item }}.TODO {{ item }}.DONE; else echo \"Failed: {{ item }}.TODO\"; fi"
        chdir: "{{ stepsdir }}"
      loop: "{{ todos1.stdout_lines }}"
      when: not complete.stat.exists
      tags: main

    - name: Run - Steps on Primary
      shell:
        cmd: "if ( sh {{ item }}.TODO ); then mv {{ item }}.TODO {{ item }}.DONE; else echo \"Failed: {{ item }}.TODO\"; fi"
        chdir: "{{ stepsdir }}"
      loop: "{{ todos2.stdout_lines }}"
      when: not complete.stat.exists
      tags: main

    - name: Remove - Running file (db2patch.running)
      file: path="{{ pvtgtdir }}/db2patch.running" state=absent
      tags: main

    - name: Create - Complete file (db2patch.complete)
      file: path="{{ pvtgtdir }}/db2patch.complete" state=touch mode=0777
      tags: main