---
## pre-req tasks

 - name: Create - Directory Structure
   file: path="{{ item }}" state=directory mode=0777
   loop: "{{ dirstocreate }}"
   tags: createdirs

 - name: Copy - Comman functions and variables file
   template: src=templates/include_db2.sh dest=/tmp/include_db2 mode=0777
   tags: copytemplate

# - name: Copy - binaries to target nodes
#   copy: src="{{ swlocaldir }}/{{ swtocopy }}" dest="{{ binariesdir }}" mode=0755 remote_src=yes
#   deligate_to: 192.168.1.105
#   tags: copybinaries

 - name: Copy - binaries to target nodes
   synchronize: src="{{ swlocaldir }}/{{ swtocopy }}" dest="{{ binariesdir }}" mode=push
   deligate_to: 192.168.1.105
   tags: copybinaries

 - name: Unzip - db2binaries
   unarchive: src="{{ binariesdir }}/{{ swtocopy }}" dest="{{ binariesdir }}" remote_src=yes
   tags: copybinaries

 - name: Copy - Scrips to target node
   copy: src="{{ item }}" dest="{{ scriptsdir }}/{{ item }}" mode=0755
   loop: "{{ scriptstocopy }}"
   tags: copyscripts
