---
    - name: Remove - Scripts from Target
      file: path="{{ scriptsdir }}/{{ item }}" state=absent
      loop: "{{ scriptstocopy }}"
      tags: cleanup      
      
    - file: path="{{ item }}" state=absent
      loop: ['/tmp/include_db2','/tmp/tsamp_chk.txt',]
      tags: cleanup