---
## pre-req tasks

- name: Create - Directory Structure
  file: path="{{ item }}" state=directory mode=0777
  loop: "{{ dirstocreate }}"
  tags: createdirs

- name: Copy - DB2 Binaries
  synchronize: src="{{ swlocaldir }}/{{ db2sw }}" dest="{{ binariesdir }}" mode=push
  delegate_to: "{{ centralhost }}"
  when: copybinaries | bool
  tags: copybinaries

- name: Unzip - DB2 Binaries
  unarchive: src="{{ binariesdir }}/{{ db2sw }}" dest="{{ binariesdir }}" remote_src=yes
  when: copybinaries | bool
  tags: copybinaries

- name: Copy - Scrips
  copy: src="{{ item }}" dest="{{ scriptsdir }}/{{ item }}" mode=0755
  loop: "{{ scriptstocopy }}"
  tags: copyscripts