---
    - name: "Running - DB2 Prepatch (Pre Backups to {{ bkpsdir }})"
      command: "{{ scriptsdir }}/prepatch.sh {{ item }}"
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: prepatch