---
    - name: Running - Stop db2 
      command: "{{ scriptsdir }}/stop_db2.sh {{ item }}"
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: stopdb2