---
## pre-req tasks

 - name: Create - Directory Structure
   file: path="{{ item }}" state=directory owner=root group="{{ createinst['instgrp'] }}" mode=0777
   loop: "{{ dirstocreate }}"
   tags: createdirs

 - name: Create - DB2 Related Directories.
   file: path="{{ item }}" state=directory owner=root group="{{ createinst['instgrp'] }}" mode=0775
   loop: "{{ db2dirs }}"
   tags: createdirs

 - name: Create - DB2 Instance Home Directory.
   file: path="/db/home" state=directory owner="{{ createinst['instid'] }}" group="{{ createinst['instgrp'] }}" mode=0755
   tags: createdirs

 - name: Add - Instance port number to /etc/services
   lineinfile:
    path: /etc/services
    line: "db2c_{{ createinst['instid'] }}    {{ createinst['instport'] }}/tcp               #DB2 Instance Communication port"
   tags: addport

 - name: Copy - Comman functions and variables file
   template: src="templates/include_db2.sh" dest="/tmp/include_db2" mode=0777
   tags: always

 - block:
    - name: Copy - DB2 Binaries
      synchronize: src="{{ db2sw }}" dest="{{ binariesdir }}" mode=push
      delegate_to: "{{ swsrchost }}"
      register: copy_check
      async: 3600
      poll: 0

    - name: Monitor - Copy binaries job
      async_status:
      jid: "{{ copy_check.ansible_job_id }}"
      register: copy_result
      until: copy_result.finished
      retries: 60
      delay: 50

    - name: Unzip - DB2 Binaries
      unarchive: src="{{ binariesdir }}/{{ swtocopy }}" dest="{{ binariesdir }}" remote_src=yes
      register: untar_check
      async: 3600
      poll: 0
      when: ansible_distribution != "AIX"

    - name: Unzip - DB2 Binaries
      unarchive: src="{{ binariesdir }}/{{ swtocopy }}" dest="{{ binariesdir }}" remote_src=yes
      register: untar_check
      async: 3600
      poll: 0
      when: ansible_distribution == "AIX"
   
    - name: Monitor - Untar binaries job
      async_status:
      jid: "{{ untar_check.ansible_job_id }}"
      register: untar_result
      until: untar_result.finished
      retries: 60
      delay: 50
   when: copybinaries | bool
   tags: copybinaries 

 - name: Copy - DB2 Standard Scrips
   copy: src="{{ item }}" dest="{{ scriptsdir }}/{{ item }}" mode=0755
   loop: "{{ scriptstocopy }}"
   tags: copyscripts