---
## pre-req tasks

 - name: Create - Directory Structure
   file: path="{{ item }}" state=directory mode=0755
   loop: "{{ dirstocreate }}"
   tags: createdirs

 - name: Create - DB2 Related dirs.
   file: path="{{ item }}" state=directory owner="{{ createinst['instid'] }}" group="{{ createinst['instgrp'] }}" mode=0775
   loop: "{{ db2dirs }}"
   tags: createdirs

 - name: Copy - Comman functions and variables file
   template: src=templates/include_db2.sh dest=/tmp/include_db2 mode=0777
   tags: always

 - name: Copy - binaries to target nodes
   copy: src="{{ db2sw }}" dest="{{ binariesdir }}" mode=0755
   tags: copybinaries

 - name: Unzip - db2binaries
   unarchive: src="{{ binariesdir }}/{{ swtocopy }}" dest="{{ binariesdir }}" remote_src=yes
   when: ansible_distribution != "AIX"
   tags: copybinaries

 - name: Unzip - db2binaries
   shell: cd "{{ binariesdir }}";tar -xvf "{{ binariesdir }}/{{ swtocopy }}"
   when: ansible_distribution == "AIX"
   tags: copybinaries

 - name: Copy - Scrips to target node
   copy: src="{{ item }}" dest="{{ scriptsdir }}/{{ item }}" mode=0755
   loop: "{{ scriptstocopy }}"
   tags: copyscripts