---
  - name: startprimaryupgrade
    block:
      - debug: msg="DB2 Fixpack upgrade Started for Primary Servers"
        run_once: true
      - import_tasks: db2fp_std_flow.yml
      - import_tasks: failover.yml
        when: 
          - installupdate == "update" or installupdate == "install_update"
          - failback | bool
        tags: failover
    when: DBROLE == "PRIMARY"
    tags: primaryfp