- name: Install - DB2 Fixpack
  shell: |
          DB2BASEPATH=$(cat {{ bkpsdir }}/db2level_bef_*.out | grep 'installed'  | awk '{print $5'} | sed "s/..$//g" | sed "s/^.//g" | head -1)
          {{ binariesdir }}/{{ swtype }}/installFixPack -f install -b ${DB2BASEPATH} -p {{ db2vpath }} -l {{ logsdir }}/installfp_db2.log -n -y >> {{ logsdir }}/installfp_STDERR.log 2>&1
  become: true
  become_method: sudo
  async: 3600
  poll: 0
  register: db2install_check
  tags: install

- debug:
    msg: "{{ db2install_check.ansible_job_id }}"

- name: Monitor db2 installation job
  become: true
  become_method: sudo
  async_status:
    jid: "{{ db2install_check.ansible_job_id }}"
  register: db2install_RESULT
  until: db2install_RESULT.finished
  retries: 60
  delay: 60
  tags: install