---
    - name: Get - ALL Db2 instances
      shell: |
             $(/usr/local/bin/db2ls | tail  -1 | awk '{print $1"/instance/db2ilist"}') > /tmp/db2ilist.lst
             chmod 777 /tmp/db2ilist.lst;
             cat /tmp/db2ilist.lst
      register: db2ilist
      tags: always

    #- name: Info - Available DB2 Instances
    #  debug: msg="{{ db2ilist.stdout_lines }}"
    #  tags: listinst,info

    - name: Info - Going to run on ALL Instances
      debug:
        msg: "{{ scripttorun }} will run for all Instances"

    - name: Run - Script on target node - ALL Instances
      shell: |
             #/tmp/{{ script }} {{ arg1 }} {{ arg2 }} >> /tmp/{{ script }}_out.txt
             /tmp/{{ script }} >> /tmp/{{ script }}_out.txt
             chmod -f 777 /tmp/{{ script }}_out.txt
      register: cmdout
      when: (scripttype == "sh") or (scripttype == "ksh")
      failed_when: cmdout.rc > 1
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: run

    - name: Run - DB2 Script on target node - ALL Instances
      shell: |
             . $HOME/sqllib/db2profile
             db2 -tvf /tmp/{{ script }} >> /tmp/{{ script }}_out.txt
             chmod -f 777 /tmp/{{ script }}_out.txt
      register: cmdout       
      when: (scripttype == "sql") or (scripttype == "db2")
      failed_when: cmdout.rc > 1
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: run