---
    #- name: Info - Running script with DB2 Instances
    #  debug: msg="{{ db2inst }}"
    #  tags: listinst,info

    - name: Info - Going to run - ONE Instance
      debug:
        msg: "{{ scripttorun }} will run for {{ db2inst }} - Instance"

    - name: Run - Script on target node - ONE Instance
      shell: |
             /tmp/{{ script }} >> /tmp/{{ script }}_out.txt
             chmod -f 777 /tmp/{{ script }}_out.txt
      register: cmdout
      when: (scripttype == "sh") or (scripttype == "ksh")
      failed_when: cmdout.rc > 1
      become: true
      become_user: "{{ db2inst }}"
      tags: run

    - name: Run - DB2 Script on target node - ONE Instance
      shell: |
             . $HOME/sqllib/db2profile
             db2 -tvf /tmp/{{ script }} >> /tmp/{{ script }}_out.txt
             chmod -f 777 /tmp/{{ script }}_out.txt
      register: cmdout
      when: (scripttype == "sql") or (scripttype == "db2")
      failed_when: cmdout.rc > 1
      become: true
      become_user: "{{ db2inst }}"
      tags: run