---
#######################################################
##  Do not change below values until really needed   ##
#######################################################

# Patch version directory - For each patch version we will have one dir in target.
pvtgtdir: "{{ tgtdir }}/{{ pversion }}"

dirstocreate:
    - "{{ tgtdir }}"
    - "{{ pvtgtdir }}"
    - "{{ pvtgtdir }}/scripts"
    - "{{ pvtgtdir }}/logs"
    - "{{ pvtgtdir }}/steps"
    - "{{ pvtgtdir }}/backups"
    - "{{ pvtgtdir }}/binaries"

scriptsdir: "{{ pvtgtdir }}/scripts"
binariesdir: "{{ pvtgtdir }}/binaries"
stepsdir: "{{ pvtgtdir }}/steps"
scriptstocopy:
    - failover.sh
    - runasdb2.sh
    - hadr_roles.sh
    - patchdb2.sh
    - start_db2.sh
    - postpatch.sh
    - prepatch.sh
    - todolist.sh
    - stop_db2.sh