---
# vars file for db2_build
target_server: all
tgtdir: /db/db2_build
swsrchost: 192.168.1.105
swlocaldir: /root/DB2Binaries
swtocopy: v11.1.1fp1_linuxx64_universal_fixpack.tar.gz
swtype: universal
db2vpath: /opt/IBM/db2/11.1
installtsamp: true
licfile: db2ese.lic
copybinaries: true
db2install: yes

## Crate instance vars.
createinst:
  create: true
  instid: db2bbi1
  fencid: db2udf
  instgrp: dba
  instport: 50730

## Crate database related vars.
createdb:
  create: true
  name: TESTDB
  datadir: /db/data
  dbdir: /db/dbdir

db2dirs:
    - /db/home
    - /db/db2dump
    - /db/admin
    - /db/activelog
    - /db/archivelog
    - /db/overflowlog
    - /db/messagelog
    - /db/exp
    - /db/dbdir
    - /db/data