---
# vars file for db2_build
#targethost: db2build
tgtdir: /db/db2_build
swlocaldir: /root/projects
swtocopy: v11.1.4fp5_linuxx64_server_t.tar.gz
swtype: server_t
db2vpath: /opt/IBM/db2/11.1
licfile: db2ese.lic

## Crate instance vars.
createinst:
  create: yes
  instid: db2ods1
  fencid: db2udf
  instgrp: db2ods1

## Crate database related vars.
createdb:
  create: yes
  name: TESTDB
  datadir: /db/data
  dbdir: /db/dbdir

db2dirs:
    - /db/home
    - /db/db2dump
    - /db/backups
    - /db/activelogs
    - /db/archivelogs
    - /db/maint
    - /db/maint/scripts
    - /db/maint/logs
    - /db/dbdir
    - /db/data

#######################################################
##  Do not change below values until really needed   ##
#######################################################

dirstocreate:
    - "{{ tgtdir }}"
    - "{{ tgtdir }}/scripts"
    - "{{ tgtdir }}/logs"
    - "{{ tgtdir }}/binaries"

scriptsdir: "{{ tgtdir }}/scripts"
binariesdir: "{{ tgtdir }}/binaries"
logdir: "{{ tgtdir }}/logs"
db2sw: "{{ swlocaldir }}/{{ swtocopy }}"

scriptstocopy:
    - stop_db2.sh
    - create_tsamp.sh
    - create_inst.sh
    - create_db.sh
    - install_db2.sh
    - start_db2.sh
    - "{{ licfile }}"