---
    - name: Copy - Scrips to target node
      copy: src="{{ item }}" dest="/tmp/{{ item }}" mode=0755
      loop: "{{ scriptstocopy }}"
      tags: copyscripts

    - name: Validate DB2 Instance and Databases
      shell: |
              echo "Instance: $(whoami)" >> /tmp/validate_db2.sh.log
              sh /tmp/db2_val.sh >> /tmp/validate_db2.sh.log
              chmod -f 777 /tmp/validate_db2.sh.log
      register: chm
      failed_when: chm.rc > 1 
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: validatedb

    - command: cat /tmp/validate_db2.sh.log
      register: cmdout

    - name: Display - Instance and Database Validation Output
      debug: msg="{{ cmdout.stdout_lines }}"
      tags: output

    - name: Validate HADR and TSA
      shell: |
              echo "Instance: $(whoami)" >> /tmp/db2_val_ha.sh.log
              echo "-----------------------------------------------------------" >> /tmp/db2_val_ha.sh.log
              sh /tmp/db2_val.sh >> /tmp/db2_val_ha.sh.log
              chmod -f 777 /tmp/db2_val_ha.sh.log
 
      register: chm
      failed_when: chm.rc > 1
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: validateha

    - command: cat /tmp/db2_val_ha.sh.log
      register: cmdoutha

    - name: Display - HADR TSA Validation Output
      debug: msg="{{ cmdoutha.stdout_lines }}"
      tags: outputha