---
    - name: Running - DB2 Failover and Running Binds on Database
      command: "{{ scriptsdir }}/failover.sh {{ item }}"
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: failoverdb2