---
    - name: "Running - DB2 Postpatch (Post Backups to {{ bkpsdir }})"
      command: "{{ scriptsdir }}/postpatch.sh {{ item }}"
      register: postpatchcmd
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: postpatch

    - name: ERROR - DB2 Postpatch Task Failed
      fail: msg="DB2 Postpatch Task Failed - Failed please check logs"
      when: postpatchcmd.rc > 0
      tags: postpatch