---
    - name: "Running - DB2 Prepatch (Pre Backups to {{ bkpsdir }})"
      command: "{{ scriptsdir }}/prepatch.sh {{ item }}"
      register: prepatchcmd
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: prepatch

    - name: ERROR - DB2 Prepatch Task Failed
      fail: msg="DB2 Prepatch Task Failed please check logs"
      when: prepatchcmd.rc > 0
      tags: prepatch