---
    - name: Running - Start db2,upgrade db and binds on Databases
      command: "{{ scriptsdir }}/start_db2.sh {{ item }}"
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: startdb2