---
    - name: Validate Virtual IP
      shell: |
              LSSAMBEFORE="{{ bkpsdir }}/{{ item }}_lssam_bef.txt
              if [[ -s ${LSSAMBEFORE} && $(grep -c 'service' ${LSSAMBEFORE}) -gt 0 ]]; then
                NOOFONLINE=$(lssam | grep -i "service" | grep -i online | wc -l)
                if [[ ${NOOFONLINE} -eq 2 ]]; then
                  VIP=$(db2pd -ha|grep db2ip |awk -F= '{print $2}'|awk '{$0=substr($0,1,length($0)-3); print $0}'|awk -F_ '{ print $2"."$3"."$4"."$5 }')
                  IPCHK=$(ip a | grep -i ${VIP} | wc -l)
                    if [[ ${IPCHK} -gt 0 ]]; then
                      echo "VIP - ${VIP} Attached to $(hostname -f)" >> "{{ logsdir }}/after_validaton.txt"
                    fi
                  
                #elif [[ ]]
                fi
              fi
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: validatevip

    - name: Validate VIP, curret db2level and db2licm output
      shell: |
              . $HOME/sqllib/db2profile
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "Instance - {{ item }}" >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "      db2level            " >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              db2level | tail -4 >> "{{ logsdir }}/after_validaton.txt"
              echo "" >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "      db2licm            " >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              db2licm -l >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "" >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "    db2pd - -alldbs       " >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              db2pd - -alldbs >> "{{ logsdir }}/after_validaton.txt"
              echo "--------------------------" >> "{{ logsdir }}/after_validaton.txt"
              echo "" >> "{{ logsdir }}/after_validaton.txt"
              chmod -f 777 "{{ logsdir }}/after_validaton.txt"
      register: valout
      failed_when: valout.rc > 1
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: finalvalidation
